### PR TITLE
Test data

### PR DESCRIPTION
**Pull request by maxGimeno**
## Summary of Changes

tests for https://github.com/CGAL/cgal/pull/4229

### CODE REVIEW

**Comment by gdamiand** [comment]
Nice feature; is it planned to be available for any cgal branch ?

**Comment by maxGimeno** [comment]
It is supposed to be running one platform per OS (MacOS, Windows, Linux) but I only have access to one machine because of the current situation, so it's kind of stuck into this alpha version. 

Note that it is actually supposed to be only used by the release manager, to test efficiently big/problematic branches outside of the "real" testsuite, to avoid having a full batch blocked for 2 weeks because of a single branch.

**Comment by maxGimeno** [comment]
But to answer your question, yes, it is supposed to go into master one day

**Comment by gdamiand** [comment]
@maxGimeno Do you think results are correct ?
There are some errors that do not seem result from this pr.
There are several S ?

**Comment by maxGimeno** [comment]
In theory, any package that doesn't use an input should have an S. S means not impacted by the PR so not tested.
Most errors I have seen say "Missing input file", that seems to be a result from this PR.

**Comment by gdamiand** [comment]
> In theory, any package that doesn't use an input should have an S. S means not impacted by the PR so not tested.

Ok thanks.

> Most errors I have seen say "Missing input file", that seems to be a result from this PR.

Indeed; in this PR, only wlop_simplify_and_regularize_test is updated (Point_set_processing package), thus other errors are normal.

But this test does not work and this is not normal.

**Pull request closed without merging**
